EasyGhaat/Areas/MasterAdmin/Controllers/UpdateBranchServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using EasyGhaat.Models;
using System.IO;
using System.Data;
using System.Web.UI.WebControls;

namespace EasyGhaat.Areas.MasterAdmin.Controllers
{
    public class UpdateBranchServiceController : Controller
    {

        AdminContext db = new AdminContext();

        // GET: MasterAdmin/UpdateBranchService
        public ActionResult Index()
        {
            int SessionId = Convert.ToInt32(Session["AdminId"]);

            if (SessionId != 0)
            {

                return View();
            }

            return RedirectToAction("../../AdminLogin/Index");

        }


        //[HttpGet]
        //public JsonResult GetService(string sidx, string sord, int page, int rows)
        //{
        //    using (AdminContext db = new AdminContext())
        //    {
        //        int pageIndex = Convert.ToInt32(page) - 1;
        //        int pageSize = rows;
        //        var obj = db.Database.SqlQuery<Proc_GetService_Result>("Proc_GetService").ToList<Proc_GetService_Result>();

        //        int totalRecords = obj.Count();
        //        var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
        //        if (sord.ToUpper() == "DESC")
        //        {
        //            obj = obj.OrderByDescending(s => s.Id).ToList();
        //            obj = obj.Skip(pageIndex * pageSize).Take(pageSize).ToList();
        //        }
        //        else
        //        {
        //            obj = obj.OrderBy(s => s.Id).ToList();
        //            obj = obj.Skip(pageIndex * pageSize).Take(pageSize).ToList();
        //        }
        //        var jsonData = new
        //        {
        //            total = totalPages,
        //            page,
        //            records = totalRecords,
        //            rows = obj
        //        };
        //        return Json(jsonData, JsonRequestBehavior.AllowGet);
        //    }
        //}

        //Edit Product
        public string Edit(Service obj)
        {
            int Id = obj.Id;
            var Newobj = db.Services.Find(Id);
            string msg = "";

            if (Newobj != null)
            {
                Newobj.Id = obj.Id;
                Newobj.Name = obj.Name;
                Newobj.Description = obj.Description;
                Newobj.IsActive = obj.IsActive;
                db.Entry(Newobj).State = EntityState.Modified;
                db.SaveChanges();
            }
            return msg = "Saved Successfully";
        }

        //For Delete
        public string Delete(int id)
        {
            var obj = db.Services.Where(c => c.Id.Equals(id)).SingleOrDefault();
            if (obj.IsDeleted == false)
            {
                obj.Id = id;
                obj.IsDeleted = true;
                obj.IsActive = false;
                obj.CreateDate = DateTime.UtcNow;
                db.SaveChanges();
            }
            return "Deleted successfully";
        }









    }
}

EasyGhaat/Areas/MasterAdmin/Views/UpdateBranchService/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/MasterAdmin/Views/Shared/_LayoutPage1.cshtml";
}

<link href="~/jqGrid/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/jqGrid/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
<script src="~/jqGrid/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/jqGrid/Scripts/jquery-ui-1.10.4.min.js"></script>
<script src="~/jqGrid/Scripts/i18n/grid.locale-en.js"></script>
<script src="~/Scripts/jquery.jqGrid.min.js"></script>


<script type="text/javascript">
    $(document).ready(function () {


        $(function () {
            $("#grid").jqGrid({
                url: "@Url.Action("GetService", "UpdateBranchService")",
                datatype: 'json',
                mtype: 'Get',
                colNames: ['Id', 'Service Name', 'Description', 'BranchName', 'CreateDate', 'IsActive', ],
                colModel: [
                   { key: true, hidden: true, name: 'Id', index: 'Id', editable: false },
                   { key: false, name: 'Name', index: 'Name', editable: true },
                   { key: false, name: 'Description', index: 'Description', editable: true },
                   { key: false, name: 'BranchName', index: 'BranchName', editable: false },
                   { key: false, name: 'CreateDate', index: 'CreateDate', editable: false, formatter: 'date', formatoptions: { newformat: 'd/m/Y' } },
                   { key: false, name: 'IsActive', index: 'IsActive', editable: true}],

                pager: jQuery('#pager'),
                rowNum: 10,
                rowList: [10, 20, 30, 40],
                height: '100%',
                viewrecords: true,
                caption: 'Services',
                loadonce: false,
                emptyrecords: 'No records to display',
                jsonReader: {
                    root: "rows",
                    page: "page",
                    total: "total",
                    records: "records",
                    repeatitems: false,
                    Id: "0"
                },
                autowidth: true,
                multiselect: true
            }).navGrid('#pager', { edit: true, add: false, del: true, search: true, refresh: true },
                {
                    // edit options
                    zIndex: 100,
                    url: "@Url.Action("Edit", "UpdateBranchService")",
                    closeOnEscape: true,
                    closeAfterEdit: true,
                    recreateForm: true,
                    afterComplete: function (response) {
                        if (response.responseText) {
                            alert(response.responseText);
                        }
                    }
                },
                {
                    // add options
                    zIndex: 100,
                    url: "@Url.Action("Create", "UpdateBranch")",
                    closeOnEscape: true,
                    closeAfterAdd: true,
                    afterComplete: function (response) {
                        if (response.responseText) {
                            alert(response.responseText);
                        }
                    }
                },
                {
                    // delete options
                    zIndex: 100,
                    url: "@Url.Action("Delete", "UpdateBranchService")",
                    closeOnEscape: true,
                    closeAfterDelete: true,
                    recreateForm: true,
                    msg: "Are you sure you want to delete this task?",
                    afterComplete: function (response) {
                        if (response.responseText) {
                            alert(response.responseText);
                        }
                    }
                });

            //$('#btnSearch').click(function (event) {
            //    event.preventDefault();
            //    filterGrid();
            //});

        });

    });


    //function filterGrid() {
    //    var postDataValues = $("#grid").jqGrid('getGridParam', 'postData');
    //    // grab all the filter ids and values and add to the post object
    //    $('.form-control').each(function (index, item) {
    //        postDataValues[$(item).attr('id')] = $(item).val();
    //    });
    //    $('#grid').jqGrid().setGridParam({ postData: postDataValues, page: 1 }).trigger('reloadGrid');
    //}



</script>
<div class="page-wrapper">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <h4 class="page-header">
                    View/Update Service
                </h4>
                <div>
                    <table id="grid"></table>
                    <div id="pager"></div>
                </div>
            </div>
        </div>
    </div>
</div>