EasyGhaat/Areas/MasterAdmin/Controllers/AddVendorPriceListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using EasyGhaat.Models;
using System.IO;
using System.Data;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;



namespace EasyGhaat.Areas.MasterAdmin.Controllers
{
    public class AddVendorPriceListController : Controller
    {
        AdminContext db = new AdminContext();

        // GET: MasterAdmin/AddVendorPriceList


       public ActionResult Index()
        {
            int SessionId = Convert.ToInt32(Session["AdminId"]);
            if (SessionId != 0)
            {             
                return View();
            }

            return RedirectToAction("../../AdminLogin/Index");

        }

       public ActionResult Search(FormCollection frm)
        { 
            List<int> vendorIdList = new List<int>();
            int id= Convert.ToInt32(frm["ddlVendor"]);
            Session["VendorId"] = id;
            var li = db.Database.SqlQuery<Proc_GetPriceId_Result>("Proc_GetPriceId  @VendorId",
             new SqlParameter("@VendorId", id)
             ).ToList<Proc_GetPriceId_Result>();
            for (int i = 0; i <= li.Count - 1; i++)
            {
                vendorIdList.Add(li[i].id);
            }
            int[] a = vendorIdList.ToArray();
            var result = db.PriceTables.Where(b => a.Contains(b.Id) && b.IsDeleted == false);
            return View(result);
   
        }


        [HttpPost]
        public void getValues2(VendorPrice_tbl newPrice)
        {
            int vid = Convert.ToInt32(Session["VendorId"]);
            var res = db.VendorPrice_tbl.Where(vp => vp.VendorId == vid && vp.PriceId == newPrice.PriceId && vp.IsDeleted == false).SingleOrDefault();
            if (res != null)
            {
                return;
            }
            newPrice.VendorId = Convert.ToInt32(Session["VendorId"]);
            newPrice.IsDeleted = false;
            db.VendorPrice_tbl.Add(newPrice);
            db.SaveChanges();
            RedirectToAction("ViewVendorPrice/Index");          
        }


        //For Delete
        public ActionResult Delete(int id)
        {
            var obj = db.VendorPrice_tbl.Where(c => c.Id.Equals(id)).SingleOrDefault();
            if (obj != null)
            {
                obj.Id = id;
                obj.IsDeleted = true;
                db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Search");
        }



    }
}

EasyGhaat/Areas/MasterAdmin/Views/AddVendorPriceList/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/MasterAdmin/Views/Shared/_LayoutPage1.cshtml";
}

@if (TempData["Message-1"] != null)
{
    <script type="text/javascript">
        alert("Already exists");
    </script>
}




<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

<script type="text/javascript">


    $(document).ready(function () {


        bind_drp_Branch();
        $('#ddlBranch').change(function () {
            branchId = $(this).val();
            FillVendor(branchId);
        });



        });

    function bind_drp_Branch() {
        $('#ddlBranch').html('');
        $('#ddlBranch').append('<option value="0">Select Branch</option>');
        $.ajax({
            type: 'GET',
            contentType: 'application/json',
            url: "/api/GetBranchs",
            success: function (data) {
                $.each(data, function (idx, value) {
                    $('#ddlBranch').append('<option value=' + value.BranchId + '>' + value.BranchName + '</option>');
                });
            },
            error: function (xhr) {
                // sweetAlert("Oops...", "Something went wrong! " + xhr.responseText, "error");
                $('#Error_msg').html('<div class="alert alert-error" style="color: #b94a48;background-color: #f2dede;border-color: #eed3d7;"><button type="button" class="close" data-dismiss="alert">&times;</button><h4>Error in bind_drp_men_pro Method !</h4>' + xhr.responseText + '</div>');
            }
        });
    }


    function FillVendor(BranchId) { // this the code to bind Vendor
        $('#ddlVendor').html('');
        $("#ddlVendor").prop("disabled", false);
        $('#ddlVendor').append('<option value="0">Select Vendor</option>');
        $.ajax({
            type: 'GET',
            contentType: 'application/json',
            url: "/api/ViewGetVendorByBranchIds/" + BranchId,
            success: function (data) {
                $.each(data, function (idx, value) {
                    $('#ddlVendor').append('<option value=' + value.Id + '>' + value.VendorName + '</option>');
                });
            },
            error: function (xhr) {
                // sweetAlert("Oops...", "Something went wrong! " + xhr.responseText, "error");
                $('#Error_msg').html('<div class="alert alert-error" style="color: #b94a48;background-color: #f2dede;border-color: #eed3d7;"><button type="button" class="close" data-dismiss="alert">&times;</button><h4>Error in bind_drp_men_pro Method !</h4>' + xhr.responseText + '</div>');
            }
        });
    }

</script>
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h4 class="page-header">
                    Add Vendor Price
                </h4>
                <form class="form-inline" method="post" action="@Url.Action("Search","AddVendorPriceList")">
                    <div class="form-group">
                        <label>Branch  </label>
                        <select required name="ddlBranch" Class="form-control form-control-lg" id="ddlBranch">
                            <option value="">Select Branch</option>
                        </select>
                        <label>Vendor  </label>
                        <select required name="ddlVendor" Class="form-control form-control-lg" id="ddlVendor">
                            <option value="">Select Vendor</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>              
            </div>
        </div>
    </div>
</div>

EasyGhaat/Areas/MasterAdmin/Views/AddVendorPriceList/Search.cshtml
@model IEnumerable<EasyGhaat.Models.PriceTable>


@{
    ViewBag.Title = "Search";
    Layout = "~/Areas/MasterAdmin/Views/Shared/_LayoutPage1.cshtml";
}





@if (TempData["Message-1"] != null)
{
    <script type="text/javascript">
        alert("Already exists");
    </script>
}


@{
    int count = 0;
    var txtVendorPrice = "txtVendorPrice";
    var rs = 0;
    // var hdnPriceId = "txtPriceId";

}


<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

<script type="text/javascript">

    $(document).ready(function () {


        //called when key is pressed in textbox
        $(".txtp").keypress(function (e) {
            //if the letter is not digit then display error and don't type anything
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                //display error message
                $("#errmsg").html("Digits Only").show().fadeOut("slow");
                return false;
            }
        });
    });
        </script>







<script type="text/javascript">


    $(document).ready(function () {


        bind_drp_Branch();
        $('#ddlBranch').change(function () {
            branchId = $(this).val();
            FillVendor(branchId);
        });

        $('#btnSubmit').click(function () {

    
            for (var i = 0; i < tblPrice.rows.length - 1; i++) {
                var price = $("Input[id='txtVendorPrice" + i.toString() + "']").val();
                if (price == "") {
                    alert("Price Can Not be null");
                    return;
                }
            }
   

            for (var i = 0; i < tblPrice.rows.length - 1; i++) {
                var txtPriceId = $("input[id='hdnPriceId" + i.toString() + "']").val();
                var txtBoxPrice = $("Input[id='txtVendorPrice" + i.toString() + "']").val();


                data = {
                    Id: 0,
                    VendorId: 0,
                    PriceId: txtPriceId,
                    IsDeleted: null,
                    Price: txtBoxPrice
                };

                $.ajax({
                    type: "POST",
                    //contentType: "application/json; charset=utf-8;",
                    url: "/AddVendorPriceList/getValues2",
                    data: data,
                    success: function (data) {



                    },
                    error: function (xhr) {

                        $('#Error_msg').html('<div class="alert alert-error" style="color: #b94a48;background-color: #f2dede;border-color: #eed3d7;"><button type="button" class="close" data-dismiss="alert">&times;</button><h4>Error in bind_drp_men_pro Method !</h4>' + xhr.responseText + '</div>');
                    }
                });

            }
            window.location = '../../UpdateVendor/Index';
        });

    });

    function bind_drp_Branch() {
        $('#ddlBranch').html('');
        $('#ddlBranch').append('<option value="0">Select Branch</option>');
        $.ajax({
            type: 'GET',
            contentType: 'application/json',
            url: "/api/GetBranchs",
            success: function (data) {
                $.each(data, function (idx, value) {
                    $('#ddlBranch').append('<option value=' + value.BranchId + '>' + value.BranchName + '</option>');
                });
            },
            error: function (xhr) {
                // sweetAlert("Oops...", "Something went wrong! " + xhr.responseText, "error");
                $('#Error_msg').html('<div class="alert alert-error" style="color: #b94a48;background-color: #f2dede;border-color: #eed3d7;"><button type="button" class="close" data-dismiss="alert">&times;</button><h4>Error in bind_drp_men_pro Method !</h4>' + xhr.responseText + '</div>');
            }
        });
    }


    function FillVendor(BranchId) { // this the code to bind Vendor
        $('#ddlVendor').html('');
        $("#ddlVendor").prop("disabled", false);
        $('#ddlVendor').append('<option value="0">Select Vendor</option>');
        $.ajax({
            type: 'GET',
            contentType: 'application/json',
            url: "/api/ViewGetVendorByBranchIds/" + BranchId,
            success: function (data) {
                $.each(data, function (idx, value) {
                    $('#ddlVendor').append('<option value=' + value.Id + '>' + value.VendorName + '</option>');
                });
            },
            error: function (xhr) {
                // sweetAlert("Oops...", "Something went wrong! " + xhr.responseText, "error");
                $('#Error_msg').html('<div class="alert alert-error" style="color: #b94a48;background-color: #f2dede;border-color: #eed3d7;"><button type="button" class="close" data-dismiss="alert">&times;</button><h4>Error in bind_drp_men_pro Method !</h4>' + xhr.responseText + '</div>');
            }
        });
    }


</script>
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h4 class="page-header">
                    Add Vendor Price
                </h4>
                <form class="form-inline" method="post" action="@Url.Action("Search","AddVendorPriceList")">
                    <div class="form-group">
                        <label>Branch  </label>
                        <select required name="ddlBranch" Class="form-control form-control-lg" id="ddlBranch">
                            <option value="">Select Branch</option>
                        </select>
                        <label>Vendor  </label>
                        <select required name="ddlVendor" Class="form-control form-control-lg" id="ddlVendor">
                            <option value="">Select Vendor</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
                <p></p>
                @if (Model != null)
                {
                    <table class="table" id="tblPrice">
                        <thead class="thead-inverse">
                            <tr style="background-color:#2e6da4;color:white;">
                                <th><center>Image </center></th>
                                <th><center>Product </center></th>
                                <th><center>Service </center></th>
                                <th><center>Customer Price</center></th>
                                <th><center> Vendor Price </center></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                rs = count++;
                                var res = @String.Concat(txtVendorPrice, rs);
                                <tr>
                                    <td hidden="hidden"><input type="hidden" id="@String.Concat("hdnPriceId", rs)" value="@item.Id" name="hdnPriceId" />  </td>
                                    <td style="width:50px; height:50px"><center><img src="@Url.Content(item.Product.ImgUrl)" alt="" class="img-responsive"></center></td>
                                    <td><center>@item.Product.Name</center></td>
                                    <td><center>@item.Service.Name</center></td>
                                    <td><center> @item.Price</center></td>   
                                    <td><center><input type="text" class="txtp"  value="" id="@String.Concat(txtVendorPrice, rs)" name="txtVendorPrice"  /></center></td>                        
                                </tr>
                            }
                        </tbody>
                    </table>
                    <input type="submit" id="btnSubmit" name="btnSubmit" class="btn btn-primary" onclick="" value="Add" />
                }
            </div>
        </div>
    </div>
</div>