EasyGhaat/Areas/MasterAdmin/Controllers/UpperFooterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using EasyGhaat.Models;
using System.IO;
using System.Data;
using System.Web.UI.WebControls;


namespace EasyGhaat.Areas.MasterAdmin.Controllers
{
    public class UpperFooterController : Controller
    {

        AdminContext db = new AdminContext();

        // GET: MasterAdmin/UpperFooter
        public ActionResult Index()
        {
            int SessionId = Convert.ToInt32(Session["AdminId"]);

            if (SessionId != 0)
            {
                return View(db.UpperFooters.ToList());
            }

            return RedirectToAction("../../AdminLogin/Index");

        }



        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Submit(UpperFooter obj, FormCollection frm)
        {

            obj.Heading = frm["Heading"];
            obj.Content= frm["Content3"];
            obj.Icon = frm["Icon"];
            obj.ContactNumber = frm["ContactNumber"];
            db.UpperFooters.Add(obj);
            db.SaveChanges();
            TempData["Message"] = "Successfull";
            return RedirectToAction("Index");
        }



        //For Delete
        public ActionResult Delete(int id)
        {
            var obj = db.UpperFooters.Where(c => c.Id.Equals(id)).SingleOrDefault();
            db.UpperFooters.Remove(obj);
            db.SaveChanges();
            TempData["Message"] = "Successfull";
            return RedirectToAction("Index");
        }

        //For Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(db.UpperFooters.Where(c => c.Id.Equals(id)).SingleOrDefault());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection frm)
        {
            UpperFooter obj = new UpperFooter();
            obj.Id = Convert.ToInt32(frm["hdnId"]);
            obj = db.UpperFooters.Find(obj.Id);
            if (obj != null)
            {
                obj.Id = Convert.ToInt32(frm["hdnId"]);

                obj.Heading = frm["Heading"];
                obj.Content = frm["Content3"];
                obj.Icon = frm["Icon"];
                obj.ContactNumber = frm["ContactNumber"];
                db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            TempData["Message"] = "Successfull";
            return RedirectToAction("Index");
        }

    }
}

EasyGhaat/Areas/MasterAdmin/Views/UpperFooter/Edit.cshtml
@model EasyGhaat.Models.UpperFooter
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/MasterAdmin/Views/Shared/_LayoutPage1.cshtml";
}
@if (TempData["Message"] != null)
{
    <script type="text/javascript">

            alert("SuccessFull");

    </script>

}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Add UpperFooter
                </h1>

              
                    <form method="post" action="@Url.Action("Edit","UpperFooter")">
                        <div class="col-md-6">


                            <label>Heading</label>
                            <input type="text" name="Heading" value="@Model.Heading" id="Heading" required="" class="form-control" />
                            <br />
                            <label>Content</label>
                            <textarea name="Content3" rows="8" cols="8" required="" value="@Model.Content" id="Content3" class="form-control">
                                @Model.Content
                            </textarea>
                            <br />
                            <label>ContactNo</label>
                            <input type="text" name="ContactNumber" value="@Model.ContactNumber" id="ContactNumber" class="form-control" />
                            <br />
                            <label>Icon(ImagePath)</label>
                            <input name="Icon" rows="8" cols="8" required="" id="Icon" value="@Model.Icon" class="form-control"/>
                            
                 

                            <br />
                            <input type="submit" class="btn btn-primary" value="Submit" />
                            <br />
                            <input type="hidden" id="hdnId" value="@Model.Id" name="hdnId" />

                        </div>
                    </form>

                    </div>

                        </div>


                        </div>
                    </div>

EasyGhaat/Areas/MasterAdmin/Views/UpperFooter/Index.cshtml
@model IEnumerable < EasyGhaat.Models.UpperFooter>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/MasterAdmin/Views/Shared/_LayoutPage1.cshtml";
}
@if (TempData["Message"] != null)
{
    <script type="text/javascript">

            alert("SuccessFull");

    </script>

}
<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Add UpperFooter
                </h1>
                    <form method="post" action="@Url.Action("Submit","UpperFooter")">
                        <div class="col-md-6">
                       
                            <label>Heading</label>
                            <input type="text" name="Heading"  id="Heading" required="" class="form-control" />
                            <br />
                            <label>Content</label>
                            <textarea name="Content3" rows="8" cols="8" required="" id="Content3" class="form-control">
                               
                            </textarea>
                            <br />
                            <label>ContactNo</label>
                            <input type="text" name="ContactNumber"  id="ContactNumber" class="form-control" />
                            <br />
                            <label>Icon(ImagePath)</label>
                            <input name="Icon" rows="8" cols="8" required="" id="Icon"  class="form-control"/>                              
                               <lable style="color:red">* Image Size should be: 47 * 47</lable>                 
                            <br />
                            <input type="submit" class="btn btn-primary" value="Submit" />
                        </div>
                    </form>

                @if (Model != null)
                {
                    <div class="row">

                        <div class="col-lg-12">
                            <h3 class="page-header">
                                Edit UpperFooter
                            </h3>
                            <table class="table-bordered">
                                <thead>
                                    <tr style="background-color:#2e6da4;color:white;">
                                        <th><center>Image</center></th>
                                        <th><center>heading</center></th>
                                        <th><center>content</center></th>
                                        <th><center>Contact_Number</center></th>
                                        <th width="50px">Edit</th>
                                        <th width="50px">Delete</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style="width:50px; height:50px"><img src="@Url.Content(item.Icon)" alt="" class="img-responsive"></td>
                                            <td hidden="hidden">@item.Id</td>
                                            <td>@item.Heading</td>
                                            <td>@item.Content</td>
                                            <td>@item.ContactNumber</td>
                                            <td>@Html.ActionLink("Edit", "Edit", "UpperFooter", new { id = @item.Id }, null)</td>
                                            <td>@Html.ActionLink("Delete", "Delete", "UpperFooter",  new { id = @item.Id }, new { onclick = "return confirm('Do you really want to delete the  " + @item.Id + "?')" })</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
                else
                {
        
                }








            </div>
        </div>
    </div>
</div>